### ISSUE TITLE
checkState support for primitive data types

### ISSUE THREAD

**Issue by natros** [ukcrpb6/guava-postfix-plugin#17]
sometimes  i have cases like this

int result = doSomething()
checkState(result > 0)

i would like to have postfix completion for this case.

IntelliJ IDEA 13.1.5
Build #IU-135.1289, built on September 25, 2014
JRE: 1.7.0_67-b01 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

thank you.

**Comment by ukcrpb6** [comment]
Fixed in v1.1.0 [IDEA 14.0]
