### ISSUE TITLE
Include parameter name in CheckNotNull.

### ISSUE THREAD

**Issue by phxql** [ukcrpb6/guava-postfix-plugin#22]
Hi,

currently `foo.checkNotNull` expands to `checkNotNull(foo)`. Could you provide an option that it expands to `checkNotNull(foo, "foo")`?

Thanks!

**Comment by ukcrpb6** [comment]
had been considering such myself having spent the best part of a couple of days adding `checkNotNull(x, "x must not be null")` to a non-sane project :)

**Comment by yshavit** [comment]
+1

**Comment by ukcrpb6** [comment]
Added support and released (awaiting moderation from JetBrains).

Disabled by default, enabled through preferences. Message suggestions suffixes are also modifiable.

**Comment by yshavit** [comment]
Perfect, thanks!
