### ISSUE TITLE
add Objects.requireNonNull()

### ISSUE THREAD

**Issue by HonoluluHenk** [ukcrpb6/guava-postfix-plugin#24]
Hi.

It's not quite Guava, but java.util.Objects.requireNonNull() (since Java7) solves the same problem as Preconditions.checkNotNull().

Would be cool if your plugin could handle that as well.
I could totally understand, if you don't want to handle non-Guava stuff, though.

P.S.: thanks for this great plugin!

**Comment by ukcrpb6** [comment]
Thanks for the suggestion, I have added support for this in v1.1.3. Whilst it is somewhat outside the bounds of the plugin I shall leave it there until such time as there is sufficient need to warrant a separate plugin. :)
